### PR TITLE
Address bug in Database pending_updates model flattening logic

### LINKED ISSUE #2161: [Bug]:
### Terraform Version

v1.13.0

### Linode Provider Version

3.5.0

### Effected Terraform Resources

[linode_database_postgresql_v2](https://registry.terraform.io/providers/linode/linode/latest/docs/resources/database_postgresql_v2)

### Terraform Config Files

terraform {
  required_providers {
    linode = {
      source = "linode/linode"
      version = "3.5.0"
    }
  }
}

provider "linode" {
  token = "X"
}

data "linode_database_postgresql_v2" "my-db" {
  id = 312885 #can be any database created yesterday or longer ago
}

### Debug Output

not needed - can be easily reproduced

### Panic Output

not needed - can be easily reproduced

### Expected Behavior

Terraform should read the details about the database

### Actual Behavior

data.linode_database_postgresql_v2.my-db: Reading...
╷
│ Error: Provider produced invalid object
│
│ Provider "provider[\"registry.terraform.io/linode/linode\"]" produced a value for
│ data.linode_database_postgresql_v2.my-db that is not wholly known.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.

Terraform fails on plan. Tried to see the scenario with the new database (created one, then read it's details via datablock) - it worked fine. Problem is with pretty much every database created before. Our reconciliation loops noticed the problem around 7 AM UTC (today).

### Steps to Reproduce

Run the aforementioned code.

### PR DESCRIPTION
**Pull request by lgarber-akamai**
## 📝 Description

This pull request resolves an issue that caused an error when values for `pending_updates` is returned from the API.

This issue was not previously detected because e2e test databases did not live long enough to accumulate pending updates. I'm not quite sure why this wasn't picked up by unit tests.

Additionally, this PR introduces a `NewResponseOverrideClient(...)` acceptance test helper that allows for the testing of fields that aren't immediately or consistently returned by the API.

CI E2E test run: https://github.com/linode/terraform-provider-linode/actions/runs/19177082133

Resolves #2161

## ✔️ How to Test

The following test steps assume you have pulled down this PR locally.

### Integration Testing

```shell
make test-int PKG_NAME=databasemysqlv2
make test-int PKG_NAME=databasepostgresqlv2
```

### CODE REVIEW

File: linode/acceptance/provider_factories.go [hunk 1]
```diff
@@ -46,3 +47,29 @@ var HttpExternalProviders = map[string]resource.ExternalProvider{
...
+		}
+
+		muxServer, err := tf6muxserver.NewMuxServer(ctx, providers...)
+		if err != nil {
+			return nil, err
+		}
+
+		return muxServer.ProviderServer(), nil
+	},
+}
```
Comment (lgarber-akamai) [inline linode/acceptance/provider_factories.go:75]: Pulled from #2129

File: linode/acceptance/database.go [hunk 2]
```diff
@@ -72,3 +72,65 @@ func CheckPostgresDatabaseExists(name string, db *linodego.PostgresDatabase) res
...
+			return fmt.Errorf("should not find database ID %d existing after delete", id)
+		}
+
+		if apiErr, ok := err.(*linodego.Error); ok && !linodego.IsNotFound(apiErr) {
+			return fmt.Errorf("failed to get database ID %d: %s", id, err)
+		}
+	}
+
+	return nil
+}
```
Comment (lgarber-akamai) [inline linode/acceptance/database.go:136]: These aren't directly relevant to this change but I did notice the `CheckDestroy` blocks were still using `acceptance.CheckVolumeDestroy`

**Review by yec-akamai — APPROVED** [review]
Tests passed locally!
