### PR TITLE
fix: Ensure image-related fields are defined alongside `image`; adjust documentation accordingly

### LINKED ISSUE #1243: [Bug]: Inconsistent plan
### Terraform Version

1.6.6

### Linode Provider Version

2.13.0

### Effected Terraform Resources

linode_instance

### Terraform Config Files

```terraform
data "linode_kernel" "latest" {
  id = "linode/latest-64bit"
}

data "linode_instance_type" "default" {
  id = "g6-nanode-1"
}

data "linode_region" "london" {
  id = "eu-west"
}

data "linode_image" "ubuntu_23_10" {
  id = "linode/ubuntu23.10"
}

resource "linode_instance" "ubuntu_23_10" {

  type   = data.linode_instance_type.default.id
  region = data.linode_region.london.id

  tags = []

  backups_enabled = false
  swap_size       = 512

  alerts {
    cpu            = 90
    io             = 10000
    network_in     = 10
    network_out    = 10
    transfer_quota = 80
  }

  watchdog_enabled = true
}

resource "linode_instance_disk" "ubuntu_23_10_boot" {
  linode_id = linode_instance.ubuntu_23_10.id

  label      = "Boot"
  size       = data.linode_instance_type.default.disk - linode_instance.ubuntu_23_10.swap_size
  filesystem = "ext4"

  image = data.linode_image.ubuntu_23_10.id

  authorized_keys = []

  authorized_users = []

  root_pass = "foobarbazqux"
}

resource "linode_instance_disk" "ubuntu_23_10_swap" {
  linode_id = linode_instance.ubuntu_23_10.id

  label      = "Swap Image"
  size       = linode_instance.ubuntu_23_10.swap_size
  filesystem = "swap"
}

resource "linode_instance_config" "ubuntu_23_10" {
  linode_id = linode_instance.ubuntu_23_10.id

  booted = true

  label = "Ubuntu 23.10 Profile"

  virt_mode    = "paravirt"
  kernel       = data.linode_kernel.latest.id
  run_level    = "default"
  memory_limit = 0

  device {
    device_name = "sda"
    disk_id     = linode_instance_disk.ubuntu_23_10_boot.id
  }

  device {
    device_name = "sdb"
    disk_id     = linode_instance_disk.ubuntu_23_10_swap.id
  }

  root_device = "/dev/sda"

  interface {
    primary = true
    purpose = "public"
  }

  helpers {
    devtmpfs_automount = true
    distro             = true
    modules_dep        = true
    network            = true
    updatedb_disabled  = true
  }
}
```

### Debug Output

```
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # linode_instance.ubuntu_23_10 will be created
  + resource "linode_instance" "ubuntu_23_10" {
      + backups            = (known after apply)
      + backups_enabled    = false
      + boot_config_label  = (known after apply)
      + booted             = (known after apply)
      + has_user_data      = (known after apply)
      + host_uuid          = (known after apply)
      + id                 = (known after apply)
      + ip_address         = (known after apply)
      + ipv4               = (known after apply)
      + ipv6               = (known after apply)
      + label              = (known after apply)
      + migration_type     = "cold"
      + private_ip_address = (known after apply)
      + region             = "eu-west"
      + resize_disk        = false
      + shared_ipv4        = (known after apply)
      + specs              = (known after apply)
      + status             = (known after apply)
      + swap_size          = 512
      + tags               = []
      + type               = "g6-nanode-1"
      + watchdog_enabled   = true

      + alerts {
          + cpu            = 90
          + io             = 10000
          + network_in     = 10
          + network_out    = 10
          + transfer_quota = 80
        }
    }

  # linode_instance_config.ubuntu_23_10 will be created
  + resource "linode_instance_config" "ubuntu_23_10" {
      + booted       = true
      + id           = (known after apply)
      + kernel       = "linode/latest-64bit"
      + label        = "Ubuntu 23.10 Profile"
      + linode_id    = (known after apply)
      + memory_limit = 0
      + root_device  = "/dev/sda"
      + run_level    = "default"
      + virt_mode    = "paravirt"

      + device {
          + device_name = "sda"
          + disk_id     = (known after apply)
        }
      + device {
          + device_name = "sdb"
          + disk_id     = (known after apply)
        }

      + helpers {
          + devtmpfs_automount = true
          + distro             = true
          + modules_dep        = true
          + network            = true
          + updatedb_disabled  = true
        }

      + interface {
          + active  = (known after apply)
          + id      = (known after apply)
          + primary = true
          + purpose = "public"
          + vpc_id  = (known after apply)
        }
    }

  # linode_instance_disk.ubuntu_23_10_boot will be created
  + resource "linode_instance_disk" "ubuntu_23_10_boot" {
      + created    = (known after apply)
      + filesystem = "ext4"
      + id         = (known after apply)
      + image      = "linode/ubuntu23.10"
      + label      = "Boot"
      + linode_id  = (known after apply)
      + root_pass  = (sensitive value)
      + size       = 25088
      + status     = (known after apply)
      + updated    = (known after apply)
    }

  # linode_instance_disk.ubuntu_23_10_swap will be created
  + resource "linode_instance_disk" "ubuntu_23_10_swap" {
      + created    = (known after apply)
      + filesystem = "swap"
      + id         = (known after apply)
      + label      = "Swap Image"
      + linode_id  = (known after apply)
      + size       = 512
      + status     = (known after apply)
      + updated    = (known after apply)
    }

Plan: 4 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

linode_instance.ubuntu_23_10: Creating...
linode_instance.ubuntu_23_10: Still creating... [10s elapsed]
linode_instance.ubuntu_23_10: Creation complete after 15s [id=54251740]
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for linode_instance_disk.ubuntu_23_10_swap to
│ include new values learned so far during apply, provider
│ "registry.terraform.io/linode/linode" produced an invalid new value for
│ .size: was cty.NumberIntVal(512), but now cty.NumberIntVal(0).
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
╷
│ Error: Provider produced inconsistent final plan
│ 
│ When expanding the plan for linode_instance_disk.ubuntu_23_10_boot to
│ include new values learned so far during apply, provider
│ "registry.terraform.io/linode/linode" produced an invalid new value for
│ .size: was cty.NumberIntVal(512), but now cty.NumberIntVal(0).
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.
╵
```

### Panic Output

_No response_

### Expected Behavior

The plan to be consistent between plan and apply

### Actual Behavior

The swap size used to calculate the size for linode_instance_disk was 512 during the plan and 0 during the apply

### Steps to Reproduce

Just apply

### PR DESCRIPTION
**Pull request by lgarber-akamai**
## 📝 Description

This change adds validation logic to ensure every field that depends on the `image` field cannot be specified without the `image` field. Additionally, this PR updates the `linode_instance` and `linode_instance_disk` documentation to better reflect this dependency.

Resolves #1243 

## ✔️ How to Test

The following test steps assume you have cloned this PR locally.

### Automated Testing

```bash
make PKG_NAME=linode/instance int-test
make PKG_NAME=linode/instancedisk int-test
```

### Manual Testing

1. In a Terraform provider sandbox environment (e.g. dx-devenv), apply the following configuration:

```terraform
resource "linode_stackscript" "test" {
  label = "test"
  description = "Does nothing."
  script = <<EOF
#!/bin/bash
# <UDF name="var" label="An arbitrary variable." example="test" default="">
echo $VAR
EOF
  images = ["linode/ubuntu22.04"]
}

resource "linode_instance" "test" {
  region = "us-southeast"
  type = "g6-nanode-1"

  authorized_users = []
  authorized_keys = []
  swap_size = 512
  root_pass = "t3Stp4SSw0Rd!!!!!!!!!"
  stackscript_id = linode_stackscript.test.id
  stackscript_data = {
    var = "wow"
  }
}
```

2. Observe validation errors are raised for all relevant fields.
3. Apply the following configuration:

```terraform
resource "linode_stackscript" "test" {
  label = "test"
  description = "Does nothing."
  script = <<EOF
#!/bin/bash
# <UDF name="var" label="An arbitrary variable." example="test" default="">
echo $VAR
EOF
  images = ["linode/ubuntu22.04"]
}

resource "linode_instance" "test" {
  region = "us-southeast"
  type = "g6-nanode-1"
  image = "linode/ubuntu22.04"

  authorized_users = []
  authorized_keys = []
  swap_size = 512
  root_pass = "t3Stp4SSw0Rd!!!!!!!!!11111"
  stackscript_id = linode_stackscript.test.id
  stackscript_data = {
    var = "wow"
  }
}
```

4. Observe the instance provisions as normal.

### CODE REVIEW

File: linode/instance/schema_resource.go [hunk 1]
```diff
@@ -208,6 +209,7 @@ var resourceSchema = map[string]*schema.Schema{
 		Optional:      true,
 		ForceNew:      true,
 		Sensitive:     true,
+		RequiredWith:  []string{"image"},
```
Comment (lgarber-akamai) [inline linode/instance/schema_resource.go:212]: It wasn't clear from the SDKv2 documentation whether the RequiredWith relationship was uni or bidirectional, but in practice it seems to work the way we want 🙂 

Another note, the validation error raised here isn't very intuitive:

```
all of `image,stackscript_data` must be specified
```

I wonder if it'd be worth implementing a CustomizeDiff validator to make this cleaner 🤔

Comment (jriddle-linode) [reply linode/instance/schema_resource.go:212]: I'm getting a ton of testing failures due to this response. `instancedisk` runs fine but `instance` is full of failures.

Comment (lgarber-akamai) [reply linode/instance/schema_resource.go:212]: Weird, let me try it on my end

Comment (lgarber-akamai) [reply linode/instance/schema_resource.go:212]: Looks like RequiredWith only accepts absolute paths and cannot be used under nested lists according to the documentation. Since nested disks are deprecated anyway I just pushed up a PR to drop `RequiredWith` from them.

Comment (jriddle-linode) [reply linode/instance/schema_resource.go:212]: After the changes i'm still getting the error on the following tests: (huge drop from before)
```
TestAccResourceInstance_typeChangeNoDisks
TestAccResourceInstance_powerStateNoImage
TestAccResourceInstance_typeChangeDiskExplicit
```

Comment (lgarber-akamai) [reply linode/instance/schema_resource.go:212]: Looks like some of the test templates are incorrect, let me update those real quick 🙂

**Comment by lgarber-akamai** [comment]
This is _technically_ a breaking change but realistically specifying `resize_disks`, etc. at all without implicit disks is undefined behavior.

**Review by jriddle-linode — APPROVED** [review]
Looking good now, tests are passing.

**Review by zliang-akamai — APPROVED** [review]
LGTM, test passed
